version: "3.9"
services:
  db:
    image: postgres:14.8-alpine3.18
    container_name: bewise_test_pgSQL
    env_file:
      - .env
    volumes:
      - ./db_init_sql/migration.sql:/docker-entrypoint-initdb.d/001.sql
      - questions-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: bewise_test_app
    command: ["/bewise_test/app.sh"]
    ports:
      - "1234:8000"
    depends_on:
      - db
volumes:
  questions-data:
