version: "3.9"
services:
  db:
    image: postgres:14.8-alpine3.18
#    build:
#      context: ./db_init_script
    container_name: bewise_test_pgSQL
    env_file:
      - .env
#    command: ["/bewise_test/db_init_script/pgsql.sh"]
    volumes:
#      - ./db_init_script/pgsql.sh:/docker-entrypoint-initdb.d/001.sh
      - questions-data:/var/lib/postgresql/data
    command: -p 1221
    expose:
      - 1221
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: bewise_test_app
    command: ["/bewise_test/app.sh"]
    ports:
      - "1234:8000"
    depends_on:
      - db
volumes:
  questions-data:
